osx_image: xcode11.3
language: objective-c
sudo: required
branches:
  only:
  - master
  - develop
  - /^v[\d.]+$/
  except:
  - screenshot

env:
  global:
  - PROJECT="Deli.xcodeproj"
  - SCHEME="Deli"
  - FRAMEWORK="Deli"
  matrix:
  - TEST=1 DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=13.3"
  - TEST=1 DESTINATION="arch=x86_64"
  - TEST=1 DESTINATION="OS=13.3,name=Apple TV"
  - TEST=0 DESTINATION="OS=6.0,name=Apple Watch Series 4 - 40mm"

install:
- eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
- swift --version
- gem install --user-install xcodeproj -v 1.6.0

before_script:
- set -o pipefail

script:
- Supports/build-binary.sh
- Supports/build-framework.sh

before_deploy:
- carthage build --no-skip-current --verbose | xcpretty -c
- carthage archive Deli

deploy:
  provider: releases
  api_key:
    secure: HzpjoCp1/CggYfA6/y1GAMvoP+a9LwgLjZQUKWVwXsztDnRzxkxFpQ1mMPO5GZ3gwy2buMHu3DYr33t+pmcNF6M5oiBiHJdQsrWKGp/Wdzel2yXKi9TKfTOdfAPdM5og+qqW/YvQDIvj+FyzGomDE8zhV6o8wPoHBKnR5cqQyvDXa/QGTL9dMQ34udlY9gd315hgzdONWlUSrQGMmpGPQWhIN3xtjmWhTtVITq9Tz2/wdpaoVOdj0DXh90+awE+e0vkmoE0rhT7JkXOMKreOnRcoqKEyzCJjX21yDFxXf57tiVoYqIIa+26XUuq445bjkMbrfDsTHSIhV5cA/iRXTSNhHt5UkmfJbbuzC7ovZe5TiI3oGgJKCHQ+hT+b4pjnAyV4ZeZl+DhHS2HLW113ubaaqeWDxRoUuOkLz4wFnNwmJxbq3TceM+0JCkvfsg2Obbhjbh7mb6J/WzOwgyMESlA0cVpvVajw/+vyl101kGVCT/DjjJc+Xe9Q4GNikgUu40UJocZwWakBsIWvu2laqTqhqB+SnrmzGjKHTrT+9/QIcq/b7UQ9mpdZUUl1BUzqm2Fdccs8DHsIrmYHW0OpjEqTLM9bwI9SGqVBcsia+Km1if4fyk692tiKMejRI+TTW9e8G+Cu7rH0UpBBvt2sNfikyHBaGM/sijr4daaRhUY=
  file:
    - Deli.framework.zip
    - Binary/Build/portable_deli.zip
    - Binary/Build/Deli.pkg
  skip_cleanup: true
  on:
    repo: kawoou/Deli
    tags: true
